"""empty message

Revision ID: 18f4ca71e789
Revises: 1fc93512ea83
Create Date: 2017-08-08 00:23:39.787806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18f4ca71e789'
down_revision = '1fc93512ea83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('thumbfile')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbfile', sa.VARCHAR(length=511), server_default=sa.text(u"''"), nullable=False))

    # ### end Alembic commands ###
