"""add products class

Revision ID: 1fc93512ea83
Revises: acdd7fd03681
Create Date: 2017-08-07 05:02:50.956723

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1fc93512ea83'
down_revision = 'acdd7fd03681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=255), server_default=u'', nullable=False),
    sa.Column('description', sa.String(length=511), server_default='', nullable=False),
    sa.Column('tags', sa.String(length=255), server_default='', nullable=False),
    sa.Column('creator', sa.Unicode(length=127), server_default=u'', nullable=False),
    sa.Column('imagefile', sa.String(length=511), server_default='', nullable=False),
    sa.Column('thumbfile', sa.String(length=511), server_default='', nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('deliverable', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('price', sa.String(31), server_default='0.00', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
